app/urls.py
from django.contrib import admin
from django.urls import include, path

from message.views import HomePage

urlpatterns = [
    path('', HomePage.as_view(), name='homepage'),
    path('admin/', admin.site.urls),
    path('api/v1/user/', include('user.urls')),
    path('api/v1/message/', include('message.urls')),
]

message/urls.py
from django.urls import path

from message import views

app_name = 'message'

urlpatterns = [
    path('list/', views.ListMessageView.as_view(), name='list'),
    path('create/', views.CreateMessageView.as_view(), name='create'),
    path('details/<pk>', views.DetailsMessageView.as_view(), name='details'),
    path('update/<pk>', views.UpdateMessageView.as_view(), name='update'),
    path('delete/<pk>', views.DeleteMessageView.as_view(), name='delete'),
]

user/urls.py
from django.urls import path

from user import views

app_name = 'user'

urlpatterns = [
    path('create/', views.CreateUserView.as_view(), name='create'),
    path('token/', views.CreateTokenView.as_view(), name='token'),
]

message/models.py
from django.conf import settings
from django.db import models


class Message(models.Model):
    """Messages created by users"""
    content = models.CharField(max_length=160)
    views = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return f'Message id: {self.pk}, content: {self.content}'

user/models.py
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager, PermissionsMixin
)
from django.db import models


class UserManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):
        """Creates and saves new user"""

        if not email:
            raise ValueError('User must have an email address')

        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password=None):
        """Creates and saves new superuser"""

        user = self.create_user(email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    """Custom user model that supports email instead of username"""

    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'

message/views.py
from django.views.generic.list import ListView
from rest_framework import generics
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from message import serializers
from message.models import Message


class ListMessageView(generics.ListAPIView):
    """List all messages"""
    serializer_class = serializers.MessageDetailSerializer
    queryset = Message.objects.order_by('id')


class CreateMessageView(generics.CreateAPIView):
    """Create new message"""
    serializer_class = serializers.MessageSerializer
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

    def perform_create(self, serializer):
        """Create a new object"""
        serializer.save(user=self.request.user)


class DetailsMessageView(generics.RetrieveAPIView):
    """Displays selected message"""
    serializer_class = serializers.MessageDetailSerializer
    queryset = Message.objects.all()

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        # increase view counter by 1 every time message is displayed
        previous_views_count = instance.views
        instance.views = previous_views_count + 1
        instance.save()

        return Response(serializer.data)


class UpdateMessageView(generics.UpdateAPIView):
    """Updates selected message"""
    serializer_class = serializers.MessageSerializer
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    queryset = Message.objects.all()

    def perform_update(self, serializer):
        """Reset view counter every time message is updated"""
        serializer.save(views=0)


class DeleteMessageView(generics.DestroyAPIView):
    """Deletes selected message"""
    serializer_class = serializers.MessageSerializer
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    queryset = Message.objects.all()


class HomePage(ListView):
    model = Message

    ordering = ['id']

user/views.py
from rest_framework import generics
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.settings import api_settings

from user.serializers import AuthTokenSerializer, UserSerializer


class CreateUserView(generics.CreateAPIView):
    """Create new user in the system"""
    serializer_class = UserSerializer


class CreateTokenView(ObtainAuthToken):
    """Create new auth token for user"""
    serializer_class = AuthTokenSerializer
    renderer_classes = api_settings.DEFAULT_RENDERER_CLASSES

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Short Messages API</title>
</head>
<body>
<div class="container">
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4" style="text-align: center">Short Messages API</h1>
        </div>
    </div>
    <div>
        <a type="button" class="btn btn-primary btn-lg btn-block"
                href='{% url 'user:create' %}'>Create user
        </a>
        <a type="button" class="btn btn-primary btn-lg btn-block"
                href='{% url 'user:token' %}'>Request token
        </a>
        <a type="button" class="btn btn-primary btn-lg btn-block"
                href='{% url 'message:list' %}'>Messages list
        </a>
        <a type="button" class="btn btn-primary btn-lg btn-block"
                href='{% url 'message:create' %}'>Create message (require authorization)
        </a>
    </div>
    <p></p>
    {% block content %}
    {% endblock %}
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

templates/message/message_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div>
        <ul class="list-group">
            {% for message in object_list %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Id: {{ message.id }} - Content: {{ message.content }}
                    <button type="button" class="btn btn-primary">
                        Views <span class="badge badge-light">{{ message.views }}</span>
                    </button>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}